// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/auth/domain/usecase/change_password_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/features/auth/data/models/request/change-password-request-models/change-password-request-model.dart'
    as _i13;
import 'package:flower_shop/features/auth/data/models/request/reset_password_request_model/reset_password_request_model.dart'
    as _i11;
import 'package:flower_shop/features/auth/domain/models/change_password_entity.dart'
    as _i12;
import 'package:flower_shop/features/auth/domain/models/forget_password_entity.dart'
    as _i8;
import 'package:flower_shop/features/auth/domain/models/login_model.dart'
    as _i5;
import 'package:flower_shop/features/auth/domain/models/reset_password_entity.dart'
    as _i10;
import 'package:flower_shop/features/auth/domain/models/signup_model.dart'
    as _i7;
import 'package:flower_shop/features/auth/domain/models/verify_reset_code_entity.dart'
    as _i9;
import 'package:flower_shop/features/auth/domain/repos/auth_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginModel>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.LoginModel>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.LoginModel>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.LoginModel>>);

  @override
  _i3.Future<_i4.ApiResult<_i7.SignupModel>> signup({
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
              #rePassword: rePassword,
              #phone: phone,
              #gender: gender,
            }),
            returnValue: _i3.Future<_i4.ApiResult<_i7.SignupModel>>.value(
              _i6.dummyValue<_i4.ApiResult<_i7.SignupModel>>(
                this,
                Invocation.method(#signup, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #password: password,
                  #rePassword: rePassword,
                  #phone: phone,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i7.SignupModel>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.ForgotPasswordEntity>> forgotPassword(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i8.ForgotPasswordEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i8.ForgotPasswordEntity>>(
                    this,
                    Invocation.method(#forgotPassword, [email]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i8.ForgotPasswordEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i9.VerifyResetCodeEntity>> verifyResetCode(
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [code]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i9.VerifyResetCodeEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i9.VerifyResetCodeEntity>>(
                    this,
                    Invocation.method(#verifyResetCode, [code]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i9.VerifyResetCodeEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i10.ResetPasswordEntity>> resetPassword(
    _i11.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i10.ResetPasswordEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i10.ResetPasswordEntity>>(
                    this,
                    Invocation.method(#resetPassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i10.ResetPasswordEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i12.ChangePasswordEntity>> changePassword(
    _i13.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i12.ChangePasswordEntity>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i12.ChangePasswordEntity>>(
                    this,
                    Invocation.method(#changePassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i12.ChangePasswordEntity>>);
}
