// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/home/presentation/manager/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flower_shop/features/home/domain/usecase/get_best_seller_usecase.dart'
    as _i4;
import 'package:flower_shop/features/home/domain/usecase/get_categories_usecase.dart'
    as _i3;
import 'package:flower_shop/features/home/domain/usecase/get_occasions_usecase.dart'
    as _i5;
import 'package:flower_shop/features/home/domain/usecase/get_products_usecase.dart'
    as _i2;
import 'package:flower_shop/features/home/presentation/manager/factory/home_factory.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetProductsUseCase_0 extends _i1.SmartFake
    implements _i2.GetProductsUseCase {
  _FakeGetProductsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCategoriesUseCase_1 extends _i1.SmartFake
    implements _i3.GetCategoriesUseCase {
  _FakeGetCategoriesUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetBestSellerUseCase_2 extends _i1.SmartFake
    implements _i4.GetBestSellerUseCase {
  _FakeGetBestSellerUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOccasionsUseCase_3 extends _i1.SmartFake
    implements _i5.GetOccasionsUseCase {
  _FakeGetOccasionsUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeFactory extends _i1.Mock implements _i6.HomeFactory {
  MockHomeFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetProductsUseCase products() =>
      (super.noSuchMethod(
            Invocation.method(#products, []),
            returnValue: _FakeGetProductsUseCase_0(
              this,
              Invocation.method(#products, []),
            ),
          )
          as _i2.GetProductsUseCase);

  @override
  _i3.GetCategoriesUseCase categories() =>
      (super.noSuchMethod(
            Invocation.method(#categories, []),
            returnValue: _FakeGetCategoriesUseCase_1(
              this,
              Invocation.method(#categories, []),
            ),
          )
          as _i3.GetCategoriesUseCase);

  @override
  _i4.GetBestSellerUseCase bestSeller() =>
      (super.noSuchMethod(
            Invocation.method(#bestSeller, []),
            returnValue: _FakeGetBestSellerUseCase_2(
              this,
              Invocation.method(#bestSeller, []),
            ),
          )
          as _i4.GetBestSellerUseCase);

  @override
  _i5.GetOccasionsUseCase occasions() =>
      (super.noSuchMethod(
            Invocation.method(#occasions, []),
            returnValue: _FakeGetOccasionsUseCase_3(
              this,
              Invocation.method(#occasions, []),
            ),
          )
          as _i5.GetOccasionsUseCase);
}
