// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/home/presentation/manager/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flower_shop/app/core/network/api_result.dart' as _i8;
import 'package:flower_shop/features/home/domain/models/best_seller_model.dart'
    as _i11;
import 'package:flower_shop/features/home/domain/models/category_model.dart'
    as _i9;
import 'package:flower_shop/features/home/domain/models/occasion_model.dart'
    as _i12;
import 'package:flower_shop/features/home/domain/models/product_model.dart'
    as _i13;
import 'package:flower_shop/features/home/domain/usecase/get_best_seller_usecase.dart'
    as _i4;
import 'package:flower_shop/features/home/domain/usecase/get_categories_usecase.dart'
    as _i3;
import 'package:flower_shop/features/home/domain/usecase/get_occasions_usecase.dart'
    as _i5;
import 'package:flower_shop/features/home/domain/usecase/get_products_usecase.dart'
    as _i2;
import 'package:flower_shop/features/home/presentation/manager/factory/home_factory.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetProductsUseCase_0 extends _i1.SmartFake
    implements _i2.GetProductsUseCase {
  _FakeGetProductsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCategoriesUseCase_1 extends _i1.SmartFake
    implements _i3.GetCategoriesUseCase {
  _FakeGetCategoriesUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetBestSellerUseCase_2 extends _i1.SmartFake
    implements _i4.GetBestSellerUseCase {
  _FakeGetBestSellerUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOccasionsUseCase_3 extends _i1.SmartFake
    implements _i5.GetOccasionsUseCase {
  _FakeGetOccasionsUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeFactory extends _i1.Mock implements _i6.HomeFactory {
  MockHomeFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetProductsUseCase products() =>
      (super.noSuchMethod(
            Invocation.method(#products, []),
            returnValue: _FakeGetProductsUseCase_0(
              this,
              Invocation.method(#products, []),
            ),
          )
          as _i2.GetProductsUseCase);

  @override
  _i3.GetCategoriesUseCase categories() =>
      (super.noSuchMethod(
            Invocation.method(#categories, []),
            returnValue: _FakeGetCategoriesUseCase_1(
              this,
              Invocation.method(#categories, []),
            ),
          )
          as _i3.GetCategoriesUseCase);

  @override
  _i4.GetBestSellerUseCase bestSeller() =>
      (super.noSuchMethod(
            Invocation.method(#bestSeller, []),
            returnValue: _FakeGetBestSellerUseCase_2(
              this,
              Invocation.method(#bestSeller, []),
            ),
          )
          as _i4.GetBestSellerUseCase);

  @override
  _i5.GetOccasionsUseCase occasions() =>
      (super.noSuchMethod(
            Invocation.method(#occasions, []),
            returnValue: _FakeGetOccasionsUseCase_3(
              this,
              Invocation.method(#occasions, []),
            ),
          )
          as _i5.GetOccasionsUseCase);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i3.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.ApiResult<List<_i9.CategoryModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i7.Future<_i8.ApiResult<List<_i9.CategoryModel>>>.value(
                  _i10.dummyValue<_i8.ApiResult<List<_i9.CategoryModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i7.Future<_i8.ApiResult<List<_i9.CategoryModel>>>);
}

/// A class which mocks [GetBestSellerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBestSellerUseCase extends _i1.Mock
    implements _i4.GetBestSellerUseCase {
  MockGetBestSellerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.ApiResult<List<_i11.BestSellerModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i7.Future<_i8.ApiResult<List<_i11.BestSellerModel>>>.value(
                  _i10.dummyValue<_i8.ApiResult<List<_i11.BestSellerModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i7.Future<_i8.ApiResult<List<_i11.BestSellerModel>>>);
}

/// A class which mocks [GetOccasionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOccasionsUseCase extends _i1.Mock
    implements _i5.GetOccasionsUseCase {
  MockGetOccasionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.ApiResult<List<_i12.OccasionModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i7.Future<_i8.ApiResult<List<_i12.OccasionModel>>>.value(
                  _i10.dummyValue<_i8.ApiResult<List<_i12.OccasionModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i7.Future<_i8.ApiResult<List<_i12.OccasionModel>>>);
}

/// A class which mocks [GetProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsUseCase extends _i1.Mock
    implements _i2.GetProductsUseCase {
  MockGetProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.ApiResult<List<_i13.ProductModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i7.Future<_i8.ApiResult<List<_i13.ProductModel>>>.value(
                  _i10.dummyValue<_i8.ApiResult<List<_i13.ProductModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i7.Future<_i8.ApiResult<List<_i13.ProductModel>>>);
}
