// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/auth/presentation/signup/manager/signup_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_shop/app/core/network/api_result.dart' as _i5;
import 'package:flower_shop/features/auth/domain/models/signup_model.dart'
    as _i6;
import 'package:flower_shop/features/auth/domain/repos/auth_repo.dart' as _i2;
import 'package:flower_shop/features/auth/domain/usecase/signup_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepo_0 extends _i1.SmartFake implements _i2.AuthRepo {
  _FakeAuthRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignupUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupUsecase extends _i1.Mock implements _i3.SignupUsecase {
  MockSignupUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeAuthRepo_0(this, Invocation.getter(#authRepo)),
          )
          as _i2.AuthRepo);

  @override
  set authRepo(_i2.AuthRepo? _authRepo) => super.noSuchMethod(
    Invocation.setter(#authRepo, _authRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.SignupModel>> call({
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
              #rePassword: rePassword,
              #phone: phone,
              #gender: gender,
            }),
            returnValue: _i4.Future<_i5.ApiResult<_i6.SignupModel>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.SignupModel>>(
                this,
                Invocation.method(#call, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #password: password,
                  #rePassword: rePassword,
                  #phone: phone,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.SignupModel>>);
}
