// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/edit_profile/api/editProfileDataScource_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i6;
import 'package:flower_shop/features/edit_profile/data/datascources/edit_profile_datasource.dart'
    as _i3;
import 'package:flower_shop/features/edit_profile/data/models/request/editprofile_request/edit_profile_request.dart'
    as _i5;
import 'package:flower_shop/features/edit_profile/data/models/response/editprofile_response/edit_profile_resonse.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEditProfileResponse_0 extends _i1.SmartFake
    implements _i2.EditProfileResponse {
  _FakeEditProfileResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileDataSource extends _i1.Mock
    implements _i3.EditProfileDataSource {
  MockEditProfileDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.EditProfileResponse> editProfile({
    required String? token,
    _i5.EditProfileRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #token: token,
              #request: request,
            }),
            returnValue: _i4.Future<_i2.EditProfileResponse>.value(
              _FakeEditProfileResponse_0(
                this,
                Invocation.method(#editProfile, [], {
                  #token: token,
                  #request: request,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.EditProfileResponse>);

  @override
  _i4.Future<_i2.EditProfileResponse> uploadPhoto({
    required String? token,
    required _i6.MultipartFile? photo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [], {#token: token, #photo: photo}),
            returnValue: _i4.Future<_i2.EditProfileResponse>.value(
              _FakeEditProfileResponse_0(
                this,
                Invocation.method(#uploadPhoto, [], {
                  #token: token,
                  #photo: photo,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.EditProfileResponse>);
}
