// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/e_commerce/presentation/categories/manager/all_categories_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_shop/app/core/network/api_result.dart' as _i5;
import 'package:flower_shop/features/e_commerce/domain/models/all_categories_model.dart'
    as _i6;
import 'package:flower_shop/features/e_commerce/domain/repos/ecommerce_repo.dart'
    as _i2;
import 'package:flower_shop/features/e_commerce/domain/usecase/all_categories_usecase.dart'
    as _i3;
import 'package:flower_shop/features/e_commerce/domain/usecase/get_product_usecase.dart'
    as _i8;
import 'package:flower_shop/features/home/domain/models/product_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEcommerceRepo_0 extends _i1.SmartFake implements _i2.EcommerceRepo {
  _FakeEcommerceRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AllCategoriesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllCategoriesUsecase extends _i1.Mock
    implements _i3.AllCategoriesUsecase {
  MockAllCategoriesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EcommerceRepo get categoriesRepo =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesRepo),
            returnValue: _FakeEcommerceRepo_0(
              this,
              Invocation.getter(#categoriesRepo),
            ),
          )
          as _i2.EcommerceRepo);

  @override
  set categoriesRepo(_i2.EcommerceRepo? _categoriesRepo) => super.noSuchMethod(
    Invocation.setter(#categoriesRepo, _categoriesRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.AllCategoriesModel>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.ApiResult<_i6.AllCategoriesModel>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i6.AllCategoriesModel>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i6.AllCategoriesModel>>);
}

/// A class which mocks [GetProductUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductUsecase extends _i1.Mock implements _i8.GetProductUsecase {
  MockGetProductUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResult<List<_i9.ProductModel>>> call({
    String? occasion,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #occasion: occasion,
              #category: category,
            }),
            returnValue:
                _i4.Future<_i5.ApiResult<List<_i9.ProductModel>>>.value(
                  _i7.dummyValue<_i5.ApiResult<List<_i9.ProductModel>>>(
                    this,
                    Invocation.method(#call, [], {
                      #occasion: occasion,
                      #category: category,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<List<_i9.ProductModel>>>);
}
