// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/home/presentation/manager/factory/home_factory_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/features/home/domain/models/best_seller_model.dart'
    as _i10;
import 'package:flower_shop/features/home/domain/models/category_model.dart'
    as _i8;
import 'package:flower_shop/features/home/domain/models/occasion_model.dart'
    as _i12;
import 'package:flower_shop/features/home/domain/models/product_model.dart'
    as _i5;
import 'package:flower_shop/features/home/domain/usecase/get_best_seller_usecase.dart'
    as _i9;
import 'package:flower_shop/features/home/domain/usecase/get_categories_usecase.dart'
    as _i7;
import 'package:flower_shop/features/home/domain/usecase/get_occasions_usecase.dart'
    as _i11;
import 'package:flower_shop/features/home/domain/usecase/get_products_usecase.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetProductsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsUseCase extends _i1.Mock
    implements _i2.GetProductsUseCase {
  MockGetProductsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i5.ProductModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i5.ProductModel>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i5.ProductModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i5.ProductModel>>>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i7.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i8.CategoryModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i8.CategoryModel>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i8.CategoryModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i8.CategoryModel>>>);
}

/// A class which mocks [GetBestSellerUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBestSellerUseCase extends _i1.Mock
    implements _i9.GetBestSellerUseCase {
  MockGetBestSellerUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i10.BestSellerModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i10.BestSellerModel>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i10.BestSellerModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i10.BestSellerModel>>>);
}

/// A class which mocks [GetOccasionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOccasionsUseCase extends _i1.Mock
    implements _i11.GetOccasionsUseCase {
  MockGetOccasionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<List<_i12.OccasionModel>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.ApiResult<List<_i12.OccasionModel>>>.value(
                  _i6.dummyValue<_i4.ApiResult<List<_i12.OccasionModel>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<List<_i12.OccasionModel>>>);
}
