// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/auth/data/repos/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/features/auth/data/datasource/auth_remote_datasource.dart'
    as _i2;
import 'package:flower_shop/features/auth/data/models/request/change-password-request-models/change-password-request-model.dart'
    as _i17;
import 'package:flower_shop/features/auth/data/models/request/forget_password_request_model/forget_password_request_model.dart'
    as _i10;
import 'package:flower_shop/features/auth/data/models/request/login_request_model.dart'
    as _i6;
import 'package:flower_shop/features/auth/data/models/request/reset_password_request_model/reset_password_request_model.dart'
    as _i14;
import 'package:flower_shop/features/auth/data/models/request/verify_reset_code_request_model/verify_reset_code_request.dart'
    as _i12;
import 'package:flower_shop/features/auth/data/models/response/change-password-response-models/change-password-response-model.dart'
    as _i16;
import 'package:flower_shop/features/auth/data/models/response/forget_password_response_model/forget_password_response_model.dart'
    as _i9;
import 'package:flower_shop/features/auth/data/models/response/login_response_model.dart'
    as _i5;
import 'package:flower_shop/features/auth/data/models/response/logout_response_model.dart'
    as _i15;
import 'package:flower_shop/features/auth/data/models/response/reset_password_response_model/reset_password_response_model.dart'
    as _i13;
import 'package:flower_shop/features/auth/data/models/response/signup_dto.dart'
    as _i7;
import 'package:flower_shop/features/auth/data/models/response/verify_reset_code_response_model/verify_reset_code_response_model.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i2.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.LoginResponse>?> login(
    _i6.LoginRequest? loginRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequest]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.LoginResponse>?>.value(),
          )
          as _i3.Future<_i4.ApiResult<_i5.LoginResponse>?>);

  @override
  _i3.Future<_i4.ApiResult<_i7.SignupDto>> signUp({
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? rePassword,
    String? phone,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
              #rePassword: rePassword,
              #phone: phone,
              #gender: gender,
            }),
            returnValue: _i3.Future<_i4.ApiResult<_i7.SignupDto>>.value(
              _i8.dummyValue<_i4.ApiResult<_i7.SignupDto>>(
                this,
                Invocation.method(#signUp, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #password: password,
                  #rePassword: rePassword,
                  #phone: phone,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i7.SignupDto>>);

  @override
  _i3.Future<_i4.ApiResult<_i9.ForgotPasswordResponse>?> forgotPassword(
    _i10.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i9.ForgotPasswordResponse>?>.value(),
          )
          as _i3.Future<_i4.ApiResult<_i9.ForgotPasswordResponse>?>);

  @override
  _i3.Future<_i4.ApiResult<_i11.VerifyResetCodeResponse>?> verifyResetCode(
    _i12.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue:
                _i3.Future<
                  _i4.ApiResult<_i11.VerifyResetCodeResponse>?
                >.value(),
          )
          as _i3.Future<_i4.ApiResult<_i11.VerifyResetCodeResponse>?>);

  @override
  _i3.Future<_i4.ApiResult<_i13.ResetPasswordResponse>> resetPassword(
    _i14.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i13.ResetPasswordResponse>>.value(
                  _i8.dummyValue<_i4.ApiResult<_i13.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#resetPassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i13.ResetPasswordResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i15.LogoutResponse>> logout({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#token: token}),
            returnValue: _i3.Future<_i4.ApiResult<_i15.LogoutResponse>>.value(
              _i8.dummyValue<_i4.ApiResult<_i15.LogoutResponse>>(
                this,
                Invocation.method(#logout, [], {#token: token}),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i15.LogoutResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i16.ChangePasswordResponse>> changePassword(
    _i17.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue:
                _i3.Future<_i4.ApiResult<_i16.ChangePasswordResponse>>.value(
                  _i8.dummyValue<_i4.ApiResult<_i16.ChangePasswordResponse>>(
                    this,
                    Invocation.method(#changePassword, [request]),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i16.ChangePasswordResponse>>);
}
