// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/orders/presentation/manager/cart_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_shop/app/core/network/api_result.dart' as _i5;
import 'package:flower_shop/features/orders/domain/models/user_carts_model.dart'
    as _i6;
import 'package:flower_shop/features/orders/domain/repos/orders_repo.dart'
    as _i2;
import 'package:flower_shop/features/orders/domain/usecase/add_product_to_cart_usecase.dart'
    as _i8;
import 'package:flower_shop/features/orders/domain/usecase/delete_cart_item_usecase.dart'
    as _i9;
import 'package:flower_shop/features/orders/domain/usecase/get_user_carts_usecase.dart'
    as _i3;
import 'package:flower_shop/features/orders/domain/usecase/update_cart_item_quantity_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrdersRepo_0 extends _i1.SmartFake implements _i2.OrdersRepo {
  _FakeOrdersRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserCartsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserCartsUsecase extends _i1.Mock
    implements _i3.GetUserCartsUsecase {
  MockGetUserCartsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdersRepo get ordersRepo =>
      (super.noSuchMethod(
            Invocation.getter(#ordersRepo),
            returnValue: _FakeOrdersRepo_0(
              this,
              Invocation.getter(#ordersRepo),
            ),
          )
          as _i2.OrdersRepo);

  @override
  set ordersRepo(_i2.OrdersRepo? _ordersRepo) => super.noSuchMethod(
    Invocation.setter(#ordersRepo, _ordersRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.UserCartsModel>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserCartsModel>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>);
}

/// A class which mocks [AddProductToCartUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProductToCartUsecase extends _i1.Mock
    implements _i8.AddProductToCartUsecase {
  MockAddProductToCartUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdersRepo get ordersRepo =>
      (super.noSuchMethod(
            Invocation.getter(#ordersRepo),
            returnValue: _FakeOrdersRepo_0(
              this,
              Invocation.getter(#ordersRepo),
            ),
          )
          as _i2.OrdersRepo);

  @override
  set ordersRepo(_i2.OrdersRepo? _ordersRepo) => super.noSuchMethod(
    Invocation.setter(#ordersRepo, _ordersRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.UserCartsModel>> call({
    String? product,
    int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #product: product,
              #quantity: quantity,
            }),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserCartsModel>>(
                this,
                Invocation.method(#call, [], {
                  #product: product,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>);
}

/// A class which mocks [DeleteCartItemUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCartItemUsecase extends _i1.Mock
    implements _i9.DeleteCartItemUsecase {
  MockDeleteCartItemUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdersRepo get ordersRepo =>
      (super.noSuchMethod(
            Invocation.getter(#ordersRepo),
            returnValue: _FakeOrdersRepo_0(
              this,
              Invocation.getter(#ordersRepo),
            ),
          )
          as _i2.OrdersRepo);

  @override
  set ordersRepo(_i2.OrdersRepo? _ordersRepo) => super.noSuchMethod(
    Invocation.setter(#ordersRepo, _ordersRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.UserCartsModel>> call({String? cartItemId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#cartItemId: cartItemId}),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserCartsModel>>(
                this,
                Invocation.method(#call, [], {#cartItemId: cartItemId}),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>);
}

/// A class which mocks [UpdateCartItemQuantityUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCartItemQuantityUsecase extends _i1.Mock
    implements _i10.UpdateCartItemQuantityUsecase {
  MockUpdateCartItemQuantityUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrdersRepo get ordersRepo =>
      (super.noSuchMethod(
            Invocation.getter(#ordersRepo),
            returnValue: _FakeOrdersRepo_0(
              this,
              Invocation.getter(#ordersRepo),
            ),
          )
          as _i2.OrdersRepo);

  @override
  set ordersRepo(_i2.OrdersRepo? _ordersRepo) => super.noSuchMethod(
    Invocation.setter(#ordersRepo, _ordersRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.ApiResult<_i6.UserCartsModel>> call({
    String? cartItemId,
    int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #cartItemId: cartItemId,
              #quantity: quantity,
            }),
            returnValue: _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>.value(
              _i7.dummyValue<_i5.ApiResult<_i6.UserCartsModel>>(
                this,
                Invocation.method(#call, [], {
                  #cartItemId: cartItemId,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<_i6.UserCartsModel>>);
}
