// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/edit_profile/presentation/manager/editProfileCubit/editProfileCubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_shop/app/config/auth_storage/auth_storage.dart' as _i8;
import 'package:flower_shop/app/core/network/api_result.dart' as _i5;
import 'package:flower_shop/features/auth/domain/models/user_model.dart' as _i9;
import 'package:flower_shop/features/edit_profile/data/models/response/editprofile_response/edit_profile_resonse.dart'
    as _i6;
import 'package:flower_shop/features/edit_profile/domain/repos/editProfile_repo.dart'
    as _i2;
import 'package:flower_shop/features/edit_profile/domain/usecases/edit_profile_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEditprofileRepo_0 extends _i1.SmartFake
    implements _i2.EditprofileRepo {
  _FakeEditprofileRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i3.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EditprofileRepo get editProfileRepo =>
      (super.noSuchMethod(
            Invocation.getter(#editProfileRepo),
            returnValue: _FakeEditprofileRepo_0(
              this,
              Invocation.getter(#editProfileRepo),
            ),
          )
          as _i2.EditprofileRepo);

  @override
  _i4.Future<_i5.ApiResult<_i6.EditProfileResponse>> call({
    required String? token,
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #token: token,
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
            }),
            returnValue:
                _i4.Future<_i5.ApiResult<_i6.EditProfileResponse>>.value(
                  _i7.dummyValue<_i5.ApiResult<_i6.EditProfileResponse>>(
                    this,
                    Invocation.method(#call, [], {
                      #token: token,
                      #firstName: firstName,
                      #lastName: lastName,
                      #email: email,
                      #phone: phone,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.ApiResult<_i6.EditProfileResponse>>);
}

/// A class which mocks [AuthStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorage extends _i1.Mock implements _i8.AuthStorage {
  MockAuthStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUser(_i9.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.UserModel?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i4.Future<_i9.UserModel?>.value(),
          )
          as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setRememberMe, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#getRememberMe, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
