// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/orders/data/repos/orders_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/features/orders/data/datasource/orders_remote_datasource.dart'
    as _i2;
import 'package:flower_shop/features/orders/data/models/user_carts_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OrdersRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersRemoteDatasource extends _i1.Mock
    implements _i2.OrdersRemoteDatasource {
  MockOrdersRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.UserCartsDto>> getUserCarts() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCarts, []),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserCartsDto>>(
                this,
                Invocation.method(#getUserCarts, []),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.UserCartsDto>> addProductToCart({
    String? product,
    int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToCart, [], {
              #product: product,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserCartsDto>>(
                this,
                Invocation.method(#addProductToCart, [], {
                  #product: product,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.UserCartsDto>> deleteCartItem({
    String? cartItemId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartItem, [], {#cartItemId: cartItemId}),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserCartsDto>>(
                this,
                Invocation.method(#deleteCartItem, [], {
                  #cartItemId: cartItemId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.UserCartsDto>> updateCartItemQuantity({
    String? cartItemId,
    int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItemQuantity, [], {
              #cartItemId: cartItemId,
              #quantity: quantity,
            }),
            returnValue: _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.UserCartsDto>>(
                this,
                Invocation.method(#updateCartItemQuantity, [], {
                  #cartItemId: cartItemId,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.UserCartsDto>>);
}
