// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/auth/api/datasource/auth_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_shop/app/core/api_manger/api_client.dart' as _i3;
import 'package:flower_shop/features/auth/data/models/request/forget_password_request_model/forget_password_request_model.dart'
    as _i9;
import 'package:flower_shop/features/auth/data/models/request/login_request_model.dart'
    as _i7;
import 'package:flower_shop/features/auth/data/models/request/reset_password_request_model/reset_password_request_model.dart'
    as _i13;
import 'package:flower_shop/features/auth/data/models/request/verify_reset_code_request_model/verify_reset_code_request.dart'
    as _i11;
import 'package:flower_shop/features/auth/data/models/response/forget_password_response_model/forget_password_response_model.dart'
    as _i8;
import 'package:flower_shop/features/auth/data/models/response/login_response_model.dart'
    as _i6;
import 'package:flower_shop/features/auth/data/models/response/logout_response_model.dart'
    as _i18;
import 'package:flower_shop/features/auth/data/models/response/reset_password_response_model/reset_password_response_model.dart'
    as _i12;
import 'package:flower_shop/features/auth/data/models/response/signup_dto.dart'
    as _i5;
import 'package:flower_shop/features/auth/data/models/response/verify_reset_code_response_model/verify_reset_code_response_model.dart'
    as _i10;
import 'package:flower_shop/features/e_commerce/data/models/response/all_categories_dto.dart'
    as _i15;
import 'package:flower_shop/features/e_commerce/data/models/response/product_details_response.dart'
    as _i17;
import 'package:flower_shop/features/e_commerce/data/models/response/products_response.dart'
    as _i14;
import 'package:flower_shop/features/home/data/models/response/home_response.dart'
    as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.SignupDto>> signUp(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [body]),
            returnValue: _i4.Future<_i2.HttpResponse<_i5.SignupDto>>.value(
              _FakeHttpResponse_0<_i5.SignupDto>(
                this,
                Invocation.method(#signUp, [body]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.SignupDto>>);

  @override
  _i4.Future<_i2.HttpResponse<_i6.LoginResponse>> login(
    _i7.LoginRequest? loginRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequest]),
            returnValue: _i4.Future<_i2.HttpResponse<_i6.LoginResponse>>.value(
              _FakeHttpResponse_0<_i6.LoginResponse>(
                this,
                Invocation.method(#login, [loginRequest]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpResponse<_i6.LoginResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i8.ForgotPasswordResponse>> forgotPassword(
    _i9.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i8.ForgotPasswordResponse>>.value(
                  _FakeHttpResponse_0<_i8.ForgotPasswordResponse>(
                    this,
                    Invocation.method(#forgotPassword, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i8.ForgotPasswordResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i10.VerifyResetCodeResponse>> verifyResetCode(
    _i11.VerifyResetCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [request]),
            returnValue:
                _i4.Future<
                  _i2.HttpResponse<_i10.VerifyResetCodeResponse>
                >.value(
                  _FakeHttpResponse_0<_i10.VerifyResetCodeResponse>(
                    this,
                    Invocation.method(#verifyResetCode, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i10.VerifyResetCodeResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i12.ResetPasswordResponse>> resetPassword(
    _i13.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i12.ResetPasswordResponse>>.value(
                  _FakeHttpResponse_0<_i12.ResetPasswordResponse>(
                    this,
                    Invocation.method(#resetPassword, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i12.ResetPasswordResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i14.ProductsResponse>> getProducts({
    String? occasion,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #occasion: occasion,
              #category: category,
            }),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i14.ProductsResponse>>.value(
                  _FakeHttpResponse_0<_i14.ProductsResponse>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #occasion: occasion,
                      #category: category,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i14.ProductsResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i15.AllCategoriesDto>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i15.AllCategoriesDto>>.value(
                  _FakeHttpResponse_0<_i15.AllCategoriesDto>(
                    this,
                    Invocation.method(#getAllCategories, []),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i15.AllCategoriesDto>>);

  @override
  _i4.Future<_i2.HttpResponse<_i16.HomeResponse>> getHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeData, []),
            returnValue: _i4.Future<_i2.HttpResponse<_i16.HomeResponse>>.value(
              _FakeHttpResponse_0<_i16.HomeResponse>(
                this,
                Invocation.method(#getHomeData, []),
              ),
            ),
          )
          as _i4.Future<_i2.HttpResponse<_i16.HomeResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i17.ProductDetailsResponse>> getProductDetails(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetails, [productId]),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i17.ProductDetailsResponse>>.value(
                  _FakeHttpResponse_0<_i17.ProductDetailsResponse>(
                    this,
                    Invocation.method(#getProductDetails, [productId]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i17.ProductDetailsResponse>>);

  @override
  _i4.Future<_i2.HttpResponse<_i18.LogoutResponse>> logout({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#token: token}),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i18.LogoutResponse>>.value(
                  _FakeHttpResponse_0<_i18.LogoutResponse>(
                    this,
                    Invocation.method(#logout, [], {#token: token}),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i18.LogoutResponse>>);
}
