// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/edit_profile/domain/usecases/edit_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/features/edit_profile/data/models/response/editprofile_response/edit_profile_resonse.dart'
    as _i5;
import 'package:flower_shop/features/edit_profile/domain/repos/edit_profile_repo.dart'
    as _i2;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EditprofileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditprofileRepo extends _i1.Mock implements _i2.EditprofileRepo {
  MockEditprofileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>> editProfile({
    required String? token,
    String? firstName,
    String? lastName,
    String? email,
    String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #token: token,
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phone: phone,
            }),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i5.EditProfileResponse>>(
                    this,
                    Invocation.method(#editProfile, [], {
                      #token: token,
                      #firstName: firstName,
                      #lastName: lastName,
                      #email: email,
                      #phone: phone,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>);

  @override
  _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>> uploadPhoto({
    required String? token,
    required _i7.XFile? photo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [], {#token: token, #photo: photo}),
            returnValue:
                _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>.value(
                  _i6.dummyValue<_i4.ApiResult<_i5.EditProfileResponse>>(
                    this,
                    Invocation.method(#uploadPhoto, [], {
                      #token: token,
                      #photo: photo,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.ApiResult<_i5.EditProfileResponse>>);
}
