// Mocks generated by Mockito 5.4.6 from annotations
// in flower_shop/test/features/main_profile/domain/get_current_user_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_shop/app/core/network/api_result.dart' as _i4;
import 'package:flower_shop/features/main_profile/domain/models/profile_user_model.dart'
    as _i5;
import 'package:flower_shop/features/main_profile/domain/repos/profile_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepo extends _i1.Mock implements _i2.ProfileRepo {
  MockProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.ProfileUserModel>> getCurrentUser(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [token]),
            returnValue: _i3.Future<_i4.ApiResult<_i5.ProfileUserModel>>.value(
              _i6.dummyValue<_i4.ApiResult<_i5.ProfileUserModel>>(
                this,
                Invocation.method(#getCurrentUser, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.ApiResult<_i5.ProfileUserModel>>);
}
